prevent crash if functionText has syntax error
Due to a mistake I parsed the wrong file and node-red crashed:
```
16 Feb 09:30:51 - evalmachine.<anonymous>:1
var results = null; results = (function(msg){{"payload":[22.38,null,null,null,-18,0.22,0,0,-62,29,-733,35,896],"hwid":"374f0e41","at":"2019-02-16T08:59:41.768462122-08:00","fmt":2,"_msgid":"2f0d373f.63fa68"}
                                                       ^

SyntaxError: Unexpected token :
    at Object.createScript (vm.js:74:10)
    at runScript (/usr/src/node-red/node_modules/node-red-contrib-file-function-ext/file-function/file-function.js:111:21)
    at /usr/src/node-red/node_modules/node-red-contrib-file-function-ext/file-function/file-function.js:73:7
    at tryToString (fs.js:512:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:500:12)
```